2025-07-01 01:32:09,677 - ERROR - Failed to write data to backtest_market_data for XAUUSD (H1): UNIQUE constraint failed: backtest_market_data.time with traceback: Traceback (most recent call last):
  File "D:\brian\fx_trading_bot\src\backtesting\data_handler.py", line 101, in sync_data
    mt5_data.to_sql(table, self.db.conn, if_exists='append', index=False)
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\core\generic.py", line 3106, in to_sql
    return sql.to_sql(
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\io\sql.py", line 844, in to_sql
    return pandas_sql.to_sql(
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\io\sql.py", line 2841, in to_sql
    return table.insert(chunksize, method)
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\io\sql.py", line 1121, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\io\sql.py", line 2537, in _execute_insert
    conn.executemany(self.insert_statement(num_rows=1), data_list)
sqlite3.IntegrityError: UNIQUE constraint failed: backtest_market_data.time

2025-07-01 01:32:09,678 - ERROR - No data available for XAUUSD on H1 after sync attempt. Check MT5 connection, symbol availability, and broker data.
2025-07-01 01:32:09,722 - ERROR - Failed to write data to backtest_market_data for XAUUSD (H4): UNIQUE constraint failed: backtest_market_data.time with traceback: Traceback (most recent call last):
  File "D:\brian\fx_trading_bot\src\backtesting\data_handler.py", line 101, in sync_data
    mt5_data.to_sql(table, self.db.conn, if_exists='append', index=False)
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\core\generic.py", line 3106, in to_sql
    return sql.to_sql(
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\io\sql.py", line 844, in to_sql
    return pandas_sql.to_sql(
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\io\sql.py", line 2841, in to_sql
    return table.insert(chunksize, method)
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\io\sql.py", line 1121, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\io\sql.py", line 2537, in _execute_insert
    conn.executemany(self.insert_statement(num_rows=1), data_list)
sqlite3.IntegrityError: UNIQUE constraint failed: backtest_market_data.time

2025-07-01 01:32:09,722 - ERROR - No data available for XAUUSD on H4 after sync attempt. Check MT5 connection, symbol availability, and broker data.
2025-07-01 01:32:09,755 - ERROR - Failed to write data to backtest_market_data for XAUUSD (D1): UNIQUE constraint failed: backtest_market_data.time with traceback: Traceback (most recent call last):
  File "D:\brian\fx_trading_bot\src\backtesting\data_handler.py", line 101, in sync_data
    mt5_data.to_sql(table, self.db.conn, if_exists='append', index=False)
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\core\generic.py", line 3106, in to_sql
    return sql.to_sql(
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\io\sql.py", line 844, in to_sql
    return pandas_sql.to_sql(
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\io\sql.py", line 2841, in to_sql
    return table.insert(chunksize, method)
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\io\sql.py", line 1121, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "D:\brian\fx_trading_bot\.venv\lib\site-packages\pandas\io\sql.py", line 2537, in _execute_insert
    conn.executemany(self.insert_statement(num_rows=1), data_list)
sqlite3.IntegrityError: UNIQUE constraint failed: backtest_market_data.time

2025-07-01 01:32:09,756 - ERROR - No data available for XAUUSD on D1 after sync attempt. Check MT5 connection, symbol availability, and broker data.
2025-07-01 01:32:34,071 - ERROR - No data available for XAUUSD on M15
